services:

  postgres:
    container_name: postgres-1
    image: postgres
    environment:
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: library
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bob -d library" ]
      interval: 15s
      timeout: 10s
      retries: 5

  pgadmin:
    container_name: pgadmin-1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "server_version" ]
      interval: 15s
      timeout: 10s
      retries: 5

  libraryapp:
    container_name: libraryapp
    image: libraryapp
    build:
      context: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-1:5432/library
      SPRING_DATASOURCE_USERNAME: bob
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - postgres
      - rabbitmq
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  postgres:
  pgadmin: