server:
  port: 8080

spring:
  application:
    name: "library"

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: 'bob'
    password: 'password'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true